plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.seleniumhq.selenium:selenium-java:4.30.0'
    testImplementation 'org.assertj:assertj-core:3.25.3'
    implementation 'commons-io:commons-io:2.16.0'
    implementation 'io.qameta.allure:allure-junit5:2.25.0'
    implementation 'org.junit.jupiter:junit-jupiter-api:5.9.1'
}

test {
    useJUnitPlatform()
    systemProperties(System.getProperties())
    //Пример как еще можно задать проперти:systemProperty "baseUrl", System.getProperty("baseUrl", "https://bonigarcia.dev/selenium-webdriver-java/")
}